### ISSUE TITLE
Logo DevRomagna

### ISSUE THREAD

**Issue by nicolaiarocci** [DevRomagna/brainstorm#3]
Sarebbe utile un logo da usare un po' ovunque: sito, github, meetup, eccetera. Idee?

**Comment by nicolaiarocci** [comment]
Con un po' di fortuna @kalamun potrebbe darci una mano.

**Comment by kalamun** [comment]
@nicolaiarocci molto volentieri, se mi spieghi meglio chi siamo e cosa facciamo :-)

**Comment by nicolaiarocci** [comment]
fair enough 😄 

Dai occhiata qui: https://www.meetup.com/it-IT/DevRomagna/ 

E iscriviti!

**Comment by nicolaiarocci** [comment]
Il logo lo useremmo su meetup.com, qui su GH, sul sito (da fare, pagina singola statica molto semplice), ecc.

**Comment by AlessandroMinoccheri** [comment]
Che ne dite di creare un contest per il logo? 
Chi vuole propone un logo entro un mese (esempio) dalla data che si decide e dopo si parte con le votazioni, cosi cerchiamo di coinvolgere piu persone magari.

**Comment by nicolaiarocci** [comment]
Mi sembra una buona idea anche se bisogna poi mettere in piedi un sistema di poll, eccetera. Conoscete qualche piattaforma adatta?

**Comment by AlessandroMinoccheri** [comment]
Be si potrebbero utilizzare i sondaggi di Google, pubblichiamo qui sul repo i vari loghi.
Oppure attraverso anche i "mi piace" direttamente qui su github o sul canale slack di dev-romagna.

**Comment by nicolaiarocci** [comment]
bella l'idea di delle pull request coi logo proposti :) Lo facciamo. C'è un canale slack #devromagna? Oddio!

**Comment by AlessandroMinoccheri** [comment]
Si dentro al Grusp c'è il canale apposito di dev-romagna

**Comment by nicolaiarocci** [comment]
Non sarebbe male se il logo fosse una elaborazione del tradizionale simbolo della romagna: https://it.wikipedia.org/wiki/Caveja

Per prova l'ho buttato nel logo della org qui su GH e credo anche su meetup.com. Pensate sia una buona idea?

**Comment by nicolaiarocci** [comment]
Vedi https://github.com/DevRomagna/website/issues/2#issuecomment-332866901
