### ISSUE TITLE
Periodicità eventi

### ISSUE THREAD

**Issue by Fuminshou** [DevRomagna/brainstorm#7]
Riporto qua la discussione nata sul canale slack (copy paste brutale della conversazione): fissare o no gli eventi con cadenza periodica?

@micheleorselli : non è meglio dare agli incontri una cadenza mensile? In questo modo la gggente può organizzarsi… e se abbiamo tanti argomenti meglio, vuol dire che possiamo andare avanti per un bel po’ 

@sensorario : per caso esiste gia' un calendario? condiviso? O da condividere, ...

Per me entrambe le proposte sono valide quindi do il mio 👍

**Comment by nicolaiarocci** [comment]
sì secondo me incontri mensili sono il giusto equilibrio, con pausa estiva (luglio/agosto e fors'anche giugno). orientativamente verso terza settimana.

**Comment by Fuminshou** [comment]
Ad occhio il giovedì mi sembra il giorno migliore
Si parla del 20 aprile (già progammato), 18 maggio e 15 giugno

**Comment by sensorario** [comment]
:+1:

**Comment by nicolaiarocci** [comment]
Ok per le date. Consideriamole indicative perché ci sarà eventualmente da aggiustare in base a disponibilità di chi ci ospita.

**Comment by nicolaiarocci** [comment]
Proseguiamo con incontri mensili da Settembre a Giugno, orientativamente il terzo Giovedì del mese.
