### ISSUE TITLE
Abilitiamo project per il repo eventi?

### ISSUE THREAD

**Issue by micheleorselli** [DevRomagna/brainstorm#8]
Per i repo github è possibile abilitare project, che fornisce una kanban per organizzare i ticket. Sarà deformazione professionale però mi sembra comodo per capire al volo lo stato dei vari task-

**Comment by sensorario** [comment]
:+1:

**Comment by sensorario** [comment]
<img width="1124" alt="schermata 2017-04-13 alle 21 18 42" src="https://cloud.githubusercontent.com/assets/820248/25020476/d3efa270-208e-11e7-9801-00f90ab75aaa.png">
Vorrei suggerire delle colonne leggermente differenti. A me piace moltissimo l'uso delle colonne del PUGMI.

**Comment by nicolaiarocci** [comment]
Sono dubbioso. Altro lavoro da fare... non bastano le label con i filtri ecc.?

**Comment by micheleorselli** [comment]
Si tratta degli stessi issue visti in modo differente, kanban piuttosto che lista. Lo proponevo proprio perchè non c'è lavoro da fare in più, solo visualizzare i dati in modo diverso

**Comment by nicolaiarocci** [comment]
Ho provato a impostare una board: https://github.com/DevRomagna/eventi/projects/1

Mi pare poco efficace perché non si possono ordinare le card in nessuna maniera (se non a manina), né filtrarle. Inoltre bisogna andare nella board ed aggiungere il ticket una volta che è stato creato. A occhio non ci vedo vantaggi rispetto a filtrare/ordinare per label e milestone nella ticket list. Mi pare che qui su GH la kanban-like board sia ancora immatura (ad esempio non puoi mettere un ticket in board direttamente dalla pagina del ticket ma devi andare nella board, (ri)cercarlo, quindi spostarlo).

**Comment by micheleorselli** [comment]
ho provato a lavorarci un ma non penso di avere i permessi necessari, se lo stato è quello ok, aspettiamo tempi migliori :-)
